### ISSUE TITLE
The possibility to name the output file

### ISSUE THREAD

**Issue by Rpeter99** [gdupont1/rodin-hs#7]
Have the possibility  in a command line to have a option will take as argument the output file name.

**Comment by gdupont1** [comment]
Problem is that the tool is made for batch treatment.
This would require to have the possibility to specify an (optional) output for each input file, something like:
```
rodin-read [...] file1 -o file1.out file2 file3 -o file3.out ...
```

This may be investigated later.

**Comment by gdupont1** [comment]
After further investigation, the current (batch-oriented) architecture of the tool does not allow an easy fix for this request.

We advise to use a script to rename files as a post treatment from the tool.
